# docker-compose.pgadmin.yml
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: interacoes@ltap.ifce.edu.br
      PGADMIN_DEFAULT_PASSWORD: ltapmaracanau2025
    ports:
      - "8081:80"
    networks:
      - dspacenet
    depends_on:
      - dspacedb

