name: Deploy Backend (DSpace) - Branch develop

on:
  workflow_dispatch:
  push:
    branches:
      - develop

      
jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, dev-backend-runner]

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Derrubar containers e remover imagens antigas (preservando volumes)
        run: |
          docker compose -p d8 down --rmi all --remove-orphans

      - name: Build dos containers
        run: |
          docker compose -f docker-compose.yml -f docker-compose-cli.yml -f docker-compose-pgadmin.yml build

      - name: Subir os containers principais
        run: |
          docker compose -p d8 -f docker-compose.yml up -d
          
      - name: Subir os containers de comandos - cli
        run: |
          docker compose -p d8 -f docker-compose-cli.yml up -d

