name: Deploy Backend (DSpace) - Branch develop 10-09-2025

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, dev-backend-runner]
    env:
      JAVA_VERSION: '17'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Install Ant
        run: sudo apt-get install -y ant

      - name: Build with Maven
        run: mvn package -B

      - name: Fresh Install DSpace (ant fresh_install)
        run: |
          cd dspace/target/dspace-installer
          ant fresh_install

