name: Deploy Backend (DSpace) - Branch develop

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, dev-backend-runner]
    env:
      JAVA_VERSION: '17'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Criar arquivo local.cfg (configuração DSpace)
        run: |
          cat <<EOF > dspace/config/local.cfg
          dspace.dir=/volumes/dspaceinstall
          dspace.server.url = https://dpace.dev.interacoes.ltap.ifce.edu.br/server
          dspace.ui.url = https://angular-dspace.dev.interacoes.ltap.ifce.edu.br
          dspace.name = InterAções
          default.language = pt_BR
          db.url = jdbc:postgresql://localhost:5432/dspace
          db.username = dspace
          db.password = @abcd1234
          ldn.enabled = true
          EOF

      - name: Build with Maven
        run: mvn package

      - name: Fresh Install DSpace (ant fresh_install)
        run: |
          cd dspace/target/dspace-installer
          ant fresh_install

