name: Deploy Backend (DSpace) - Branch develop 10-09-2025

on:
  workflow_dispatch:
  push:
    branches:
      - develop

      
jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, dev-backend-runner]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Habilita cache do Maven; NÃO instala JDK no host
      - name: Setup Java cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

