name: Deploy Backend (DSpace) - Branch develop 10-09-2025

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, dev-backend-runner]
    env:
      JAVA_VERSION: '17'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java and Maven
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven
          components: ['maven']

      - name: Build with Maven
        run: mvn package -B

